# Generated by Django 3.0.2 on 2020-03-26 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nid', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('rank', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=True)),
                ('CreatedDate', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('imageTitle', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('mainNews', models.BooleanField(default=True)),
                ('sliderKey', models.BooleanField(default=True)),
                ('viewCount', models.IntegerField(blank=True, default=0, null=True)),
                ('createdBy', models.CharField(max_length=100)),
                ('updatedBy', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsportal.Category')),
            ],
            options={
                'db_table': 'news',
            },
        ),
    ]
