# Generated by Django 3.0.2 on 2020-03-26 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsportal', '0002_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='createdBy',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='CreatedDate',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='imageTitle',
            new_name='image_title',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='mainNews',
            new_name='main_news',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='sliderKey',
            new_name='slider_key',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='updatedBy',
            new_name='updated_by',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='updatedDate',
            new_name='updated_date',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='viewCount',
            new_name='view_count',
        ),
        migrations.RemoveField(
            model_name='news',
            name='Nid',
        ),
    ]
