# Generated by Django 3.0.4 on 2020-07-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsportal', '0004_category_menu_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='filteration',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
