# Generated by Django 3.0.4 on 2020-07-20 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsportal', '0005_category_filteration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='filteration',
        ),
    ]
