# Generated by Django 3.0.4 on 2020-07-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsportal', '0006_remove_category_filteration'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='filteration',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
