# Generated by Django 3.0.4 on 2020-04-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Feedback please')),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'Contactus',
            },
        ),
    ]
