# Generated by Django 3.0.4 on 2020-05-04 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contactus',
            table='contactus',
        ),
    ]
